Update ibm-connect-direct.yaml
This entry was not present in super manifest. 

Hence, entitled customers were not able to pull it. 

```
podman pull cp.icr.io/cp/ibm-connectdirect/cdu6.3_certified_container_6.3.0.4:6.3.0.4_iFix015
Trying to pull cp.icr.io/cp/ibm-connectdirect/cdu6.3_certified_container_6.3.0.4:6.3.0.4_iFix015...
Error: initializing source docker://cp.icr.io/cp/ibm-connectdirect/cdu6.3_certified_container_6.3.0.4:6.3.0.4_iFix015: reading manifest 6.3.0.4_iFix015 in cp.icr.io/cp/ibm-connectdirect/cdu6.3_certified_container_6.3.0.4: denied:

```